# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63927f598ee888e0762cf4ecd857788b90962a70b788be365cd39925aee6cb091a3ef6a227a3bf1cf95cbf1542752bb883d2de52ea2c82de4cd7291141e7a834

test:
  secret_key_base: 8d63ca7fa98eae7eee93eafb604504ec852f641a05cdf4fbdd345ae33b87a0f858b34fc16d069886e24b6b7862173a0949d65116596d3ed396026897edefca5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
